[package]
name = "aoc-2019-10"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.8.5"

[[bench]]
name = "gcd_benchmark"
harness = false
